package patches.projects

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.Project
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the root project
accordingly, and delete the patch script.
*/
changeProject(DslContext.projectId) {
    params {
        expect {
            param("AzAppId", "767d5e60-4d25-4794-9a4d-f714fab829e0")
        }
        update {
            param("AzAppId", "b9498375-0160-4831-8ce2-58f110a198ab")
        }
    }
}
